name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Replace with your default branch

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Dioxus Deploy
        uses: DioxusLabs/deploy-action@v0.1.2
        with:
          platform: web
